# 服务名称
spring:
  application:
    name: eureka-client-provider

# 服务提供者端口号
server:
  port: 7002

# 配置Eureka Server 信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
