# 服务名称
spring:
  application:
    name: eureka-client-consumer

# 服务消费者端口号
server:
  port: 7003

# 配置Eureka Server 信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
